version: "3.7"

services:
  searchengine:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3000:3000"
    command: bundle exec rails s -u puma -b 0.0.0.0
